Switch from bash to perl
Switched all bash code to perl for quicker and better DB connects.
Also use bacula dbcheck to get the database connection data without
using any munin config entries.

TODO: DB besides postgresql and multiple Catalog settings.

diff --git a/monitoring/munin/bacula_bytes_by_level b/monitoring/munin/bacula_bytes_by_level
--- a/monitoring/munin/bacula_bytes_by_level
+++ b/monitoring/munin/bacula_bytes_by_level
@@ -1,69 +1,110 @@
-#!/bin/sh
+#!/usr/bin/perl
 #
-# The MIT License
-#
-# Copyright (c) 2010 INQNET GmbH <oss@inqnet.at>
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy
-# of this software and associated documentation files (the "Software"), to deal
-# in the Software without restriction, including without limitation the rights
-# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-# copies of the Software, and to permit persons to whom the Software is
-# furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in
-# all copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
-# THE SOFTWARE.
+# (C) 2013, Clemens Schwaighofer
+# currently only works with PostgreSQL DB and only with ONE catalog database
 
+use strict;
+use warnings;
+use DBD::Pg;
+
+# get the config data from the bacula dbcheck command
+my $dir_conf='/usr/sbin/dbcheck -B -c /etc/bacula/bacula-dir.conf';
+open(FP, "$dir_conf|") or die "Can't get catalog information $@";
+my %cfg;
+while (my $l = <FP>)
+{
+	if ($l =~ /(\w+)=(.+)/)
+	{
+		$cfg{$1} = $2;
+	}
+}
+close(FP);
+# set the db connect data, a) from enviroment (munin conf), local conf (bacula) or default
+my $DBUSER = $ENV{DBUSER} || $cfg{'db_user'} || 'bacula';
+my $DBPORT = $ENV{DBPORT} || $cfg{'db_port'} || '5432';
+my $DBHOST = $ENV{DBHOST} || $cfg{'db_address'} || 'localhost';
+my $DBNAME = $ENV{DBNAME} || $cfg{'db_name'} || 'bacula';
+my $DBPASS = $ENV{DBPASS} || $cfg{'db_password'};
+
+if (defined($ARGV[0]) and ($ARGV[0] eq 'config'))
+{
+	print "graph_title Bytes consumed by backup levels\n";
+	print "graph_args --base 1024 --lower-limit 0\n";
+	print "graph_vlabel Bytes\n";
+	print "graph_category bacula\n";
+	print "graph_info Bytes by backup level\n";
+    print "graph_order incremental differential full avail free\n";
+
+	print "incremental.label Incremental\n";
+	print "incremental.draw AREA\n";
+	print "incremental.info Bytes used by incremental\n";
+
+	print "differential.label Differntial\n";
+	print "differential.draw STACK\n";
+	print "differential.info Bytes used by differential backups\n";
+
+	print "full.label Full\n";
+	print "full.draw STACK\n";
+	print "full.info Bytes used by full backups\n";
+
+	print "free.label Free\n";
+	print "free.draw STACK\n";
+	print "free.info Free bytes\n";
+
+	print "avail.label Total pool size\n";
+	print "avail.draw LINE1\n";
+	print "avail.info Available bytes in backup pool\n";
+
+	exit(0);
+}
+
+# basic data and query vars
+my $query;
+my $cursor;
+my $data;
+# connect to DB
+my $dsn = "DBI:Pg:dbname=".$DBNAME.";host=".$DBHOST.";port=".$DBPORT;
+my $dbh = DBI->connect($dsn, $DBUSER, $DBPASS) || die ("Can't connect to db $DBNAME @ $DBHOST with user $DBUSER\n");
 
 # available bytes
-AVAIL=`echo "select numvols * maxvolbytes from pool where name='Default'" | psql --pset t bacula | sed -e 's/ //g'`;
-
-if [ "$1" = "config" ]; then
-	echo "graph_title Bytes consumed by backup levels"
-	echo "graph_args --base 1024 --lower-limit 0"
-	echo 'graph_vlabel Bytes'
-	echo 'graph_category bacula'
-	echo 'graph_info Bytes by backup level'
-        echo 'graph_order incremental differential avail free'
-
-	echo 'incremental.label Incremental'
-	echo 'incremental.draw AREA'
-	echo 'incremental.info Bytes used by incremental'
-
-	echo 'differential.label Differntial'
-	echo 'differential.draw STACK'
-	echo 'differential.info Bytes used by differential backups'
-
-	echo 'free.label Free'
-	echo 'free.draw STACK'
-	echo 'free.info Free bytes'
-
-	echo 'avail.label Total pool size'
-	echo 'avail.draw LINE1'
-	echo 'avail.info Available bytes in backup pool'
-
-	exit 0
-fi
-
+$query = 'SELECT (SUM(numvols) * SUM(maxvolbytes)) AS avail FROM pool p, job j WHERE p.poolid = j.poolid';
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute() || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $AVAIL = $data->{'avail'};
 # bytes used by incremental backups
-IBYTES=`echo "select sum(jobbytes) from job where level='I' and type='B'" | psql --pset t bacula | sed -e 's/ //g'`;
+$query = "SELECT COALESCE(SUM(jobbytes), 0) AS ibytes FROM job WHERE level='I' AND type='B'";
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute() || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $IBYTES = $data->{'ibytes'};
 # bytes used by differential backups
-DBYTES=`echo "select sum(jobbytes) from job where level='D' and type='B'" | psql --pset t bacula | sed -e 's/ //g'`;
+$query = "SELECT COALESCE(SUM(jobbytes), 0) AS dbytes FROM job WHERE level='D' AND type='B'";
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute() || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $DBYTES = $data->{'dbytes'};
+# bytes used by differential backups
+$query = "SELECT COALESCE(SUM(jobbytes), 0) AS fbytes FROM job WHERE level='F' AND type='B'";
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute() || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $FBYTES = $data->{'fbytes'};
+
+if ($AVAIL == 0)
+{
+	$AVAIL = $IBYTES + $DBYTES + $FBYTES;
+}
 # Free bytes
-FREE=$(($AVAIL-$IBYTES-$DBYTES));
+my $FREE = $AVAIL - $IBYTES - $DBYTES - $FBYTES;
 
+print "avail.value $AVAIL\n";
+print "incremental.value $IBYTES\n";
+print "differential.value $DBYTES\n";
+print "full.value $FBYTES\n";
+print "free.value $FREE\n";
 
-echo "avail.value $AVAIL"
-echo "incremental.value $IBYTES"
-echo "differential.value $DBYTES"
-echo "free.value $FREE"
+$cursor->finish;
+$dbh->disconnect();
 
-exit 0
+exit(0);
diff --git a/monitoring/munin/bacula_level_bytes_day b/monitoring/munin/bacula_level_bytes_day
--- a/monitoring/munin/bacula_level_bytes_day
+++ b/monitoring/munin/bacula_level_bytes_day
@@ -1,63 +1,92 @@
-#!/bin/sh
+#!/usr/bin/perl
 #
-# The MIT License
-#
-# Copyright (c) 2010 INQNET GmbH <oss@inqnet.at>
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy
-# of this software and associated documentation files (the "Software"), to deal
-# in the Software without restriction, including without limitation the rights
-# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-# copies of the Software, and to permit persons to whom the Software is
-# furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in
-# all copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
-# THE SOFTWARE.
+# (C) 2013, Clemens Schwaighofer
+# currently only works with PostgreSQL DB and only with ONE catalog database
 
+use strict;
+use warnings;
+use DBD::Pg;
 
-# available bytes
-AVAIL=`echo "select numvols * maxvolbytes from pool where name='Default'" | psql --pset t bacula | sed -e 's/ //g'`;
+# get the config data from the bacula dbcheck command
+my $dir_conf='/usr/sbin/dbcheck -B -c /etc/bacula/bacula-dir.conf';
+open(FP, "$dir_conf|") or die "Can't get catalog information $@";
+my %cfg;
+while (my $l = <FP>)
+{
+	if ($l =~ /(\w+)=(.+)/)
+	{
+		$cfg{$1} = $2;
+	}
+}
+close(FP);
+# set the db connect data, a) from enviroment (munin conf), local conf (bacula) or default
+my $DBUSER = $ENV{DBUSER} || $cfg{'db_user'} || 'bacula';
+my $DBPORT = $ENV{DBPORT} || $cfg{'db_port'} || '5432';
+my $DBHOST = $ENV{DBHOST} || $cfg{'db_address'} || 'localhost';
+my $DBNAME = $ENV{DBNAME} || $cfg{'db_name'} || 'bacula';
+my $DBPASS = $ENV{DBPASS} || $cfg{'db_password'};
+# the backup job, will be excluded in the bytes count
+my $CATALOG = $ENV{CATALOG} || 'CatalogBackup';
 
-if [ "$1" = "config" ]; then
-	echo "graph_title Bytes consumed by backup levels per day"
-	echo "graph_args --base 1024 --lower-limit 0"
-	echo 'graph_vlabel Bytes'
-	echo 'graph_category bacula'
-	echo 'graph_info Bytes by backup level'
-        echo 'graph_order incremental differential'
+if (defined($ARGV[0]) and ($ARGV[0] eq 'config'))
+{
+	print "graph_title Bytes consumed by backup levels per day\n";
+	print "graph_args --base 1024 --lower-limit 0\n";
+	print "graph_vlabel Bytes\n";
+	print "graph_category bacula\n";
+	print "graph_info Bytes by backup level\n";
+    print "graph_order incremental differential full\n";
 
-	echo 'incremental.label Incremental'
-	echo 'incremental.draw AREA'
-	echo 'incremental.info Bytes used by incremental'
+	print "incremental.label Incremental\n";
+	print "incremental.draw AREA\n";
+	print "incremental.info Bytes used by incremental\n";
 
-	echo 'differential.label Differntial'
-	echo 'differential.draw STACK'
-	echo 'differential.info Bytes used by differential backups'
+	print "differential.label Differntial\n";
+	print "differential.draw STACK\n";
+	print "differential.info Bytes used by differential backups\n";
 
-	exit 0
-fi
+	print "full.label Full\n";
+	print "full.draw STACK\n";
+	print "full.info Bytes used by full backups\n";
+
+	exit(0);
+}
+
+# basic data and query vars
+my $query;
+my $cursor;
+my $data;
+# connect to DB
+my $dsn = "DBI:Pg:dbname=".$DBNAME.";host=".$DBHOST.";port=".$DBPORT;
+my $dbh = DBI->connect($dsn, $DBUSER, $DBPASS) || die ("Can't connect to db $DBNAME @ $DBHOST with user $DBUSER\n");
 
 ## Endtime is offsetted by one hour because all the backups start at about 2300
-## and we want aggregated statistics over a backup run and not over a day..
-## bytes used by incremental backups
-#IBYTES=`echo "select sum(jobbytes) from job where level='I' and type='B' and endtime + '1 hour'::Interval > date(current_timestamp)" | psql --pset t bacula | sed -e 's/ //g'`;
-## bytes used by differential backups
-#DBYTES=`echo "select sum(jobbytes) from job where level='D' and type='B' and endtime + '1 hour'::Interval > date(current_timestamp)" | psql --pset t bacula | sed -e 's/ //g'`;
 
-#Different logic here: We want to know the amount of jobbytes of the jobs between the current BackupCatalog and the last BackupCatalog assuming that BackupCatalog always gets scheduled as last job.
+# Different logic here: We want to know the amount of jobbytes of the jobs between the current $CATALOG and the last $CATALOG assuming that $CATALOG always gets scheduled as last job.
+# Incremental
+$query = "SELECT COALESCE(SUM(jobbytes), 0) AS ibytes FROM job WHERE level = 'I' AND type = 'B' AND jobid > (SELECT MAX(jobid) FROM job WHERE name = ? AND jobid != (SELECT MAX(jobid) FROM job WHERE name = ?))";
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute($CATALOG, $CATALOG) || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $IBYTES = $data->{'ibytes'};
+# Differential
+$query = "SELECT COALESCE(SUM(jobbytes), 0) AS dbytes FROM job WHERE level = 'D' AND type = 'B' AND jobid > (SELECT MAX(jobid) FROM job WHERE name = ? AND jobid != (SELECT MAX(jobid) FROM job WHERE name = ?))";
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute($CATALOG, $CATALOG) || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $DBYTES = $data->{'dbytes'};
+# Full
+$query = "SELECT COALESCE(SUM(jobbytes), 0) AS fbytes FROM job WHERE level = 'F' AND type = 'B' AND jobid > (SELECT MAX(jobid) FROM job WHERE name = ? AND jobid != (SELECT MAX(jobid) FROM job WHERE name = ?))";
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute($CATALOG, $CATALOG) || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $FBYTES = $data->{'fbytes'};
 
-IBYTES=`echo "select sum(jobbytes) from job where level='I' and type='B' and jobid > (select max(jobid) from job where name='BackupCatalog' and jobid != (select max(jobid) from job where name='BackupCatalog'))" | psql --pset t bacula | sed -e 's/ //g'`;
-DBYTES=`echo "select sum(jobbytes) from job where level='D' and type='B' and jobid > (select max(jobid) from job where name='BackupCatalog' and jobid != (select max(jobid) from job where name='BackupCatalog'))" | psql --pset t bacula | sed -e 's/ //g'`;
+print "incremental.value $IBYTES\n";
+print "differential.value $DBYTES\n";
+print "full.value $FBYTES\n";
 
-echo "incremental.value $IBYTES"
-echo "differential.value $DBYTES"
+$cursor->finish;
+$dbh->disconnect();
 
-exit 0
+exit(0);
diff --git a/monitoring/munin/bacula_pool_volumes_ b/monitoring/munin/bacula_pool_volumes_
--- a/monitoring/munin/bacula_pool_volumes_
+++ b/monitoring/munin/bacula_pool_volumes_
@@ -1,112 +1,162 @@
-#!/bin/sh
+#!/usr/bin/perl
 #
-# The MIT License
-#
-# Copyright (c) 2010 INQNET GmbH <oss@inqnet.at>
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy
-# of this software and associated documentation files (the "Software"), to deal
-# in the Software without restriction, including without limitation the rights
-# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-# copies of the Software, and to permit persons to whom the Software is
-# furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in
-# all copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
-# THE SOFTWARE.
+# (C) 2013, Clemens Schwaighofer
+# currently only works with PostgreSQL DB and only with ONE catalog database
+
+use strict;
+use warnings;
+use DBD::Pg;
+use File::Basename;
+
+# get the config data from the bacula dbcheck command
+my $dir_conf='/usr/sbin/dbcheck -B -c /etc/bacula/bacula-dir.conf';
+open(FP, "$dir_conf|") or die "Can't get catalog information $@";
+my %cfg;
+while (my $l = <FP>)
+{
+	if ($l =~ /(\w+)=(.+)/)
+	{
+		$cfg{$1} = $2;
+	}
+}
+close(FP);
+# set the db connect data, a) from enviroment (munin conf), local conf (bacula) or default
+my $DBUSER = $ENV{DBUSER} || $cfg{'db_user'} || 'bacula';
+my $DBPORT = $ENV{DBPORT} || $cfg{'db_port'} || '5432';
+my $DBHOST = $ENV{DBHOST} || $cfg{'db_address'} || 'localhost';
+my $DBNAME = $ENV{DBNAME} || $cfg{'db_name'} || 'bacula';
+my $DBPASS = $ENV{DBPASS} || $cfg{'db_password'};
 
 
+my $POOLNAME = File::Basename::basename($0);
+$POOLNAME =~ s/^bacula_pool_volumes_//;
+exit(1) if (!$POOLNAME);
 
-POOL=`basename $0| sed 's/^bacula_pool_volumes_//'`
-if [ ! $POOL ];then
-	exit 1
-fi
+# basic data and query vars
+my $query;
+my $cursor;
+my $data;
+# connect to DB
+my $dsn = "DBI:Pg:dbname=".$DBNAME.";host=".$DBHOST.";port=".$DBPORT;
+my $dbh = DBI->connect($dsn, $DBUSER, $DBPASS) || die ("Can't connect to db $DBNAME @ $DBHOST with user $DBUSER\n");
 
-case $POOL in
- 1) POOLNAME='Default'
-    ;;
- *) POOLNAME='Full Backups'
-    ;;
-esac
+# available bytes
+$query = "SELECT poolid FROM pool WHERE name = ?";
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute($POOLNAME) || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $POOLID = $data->{'poolid'} || 0;
 
+# max volumes in this pool, also used as TOTAL for normal output
+$query = "SELECT maxvols FROM pool WHERE poolid = ?";
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute($POOLID) || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $GRAPHLIMIT = $data->{'maxvols'} || 0;
 
+if (defined($ARGV[0]) and ($ARGV[0] eq 'config'))
+{
 
+	print "graph_title Bacula Volumes from POOL $POOLNAME\n";
+	print "graph_args --base 1000 -r --lower-limit 0 --upper-limit $GRAPHLIMIT\n";
+	print "graph_vlabel Number of volumes\n";
+	print "graph_category bacula\n";
+	print "graph_info Bacula Volume states for POOL $POOLNAME\n";
+	print "graph_scale no\n";
+    print "graph_order full append used error recycle other unused\n";
 
+	print "full.label Full\n";
+	print "full.draw AREA\n";
+	print "full.info Full and retention time not reached\n";
 
-if [ "$1" = "config" ]; then
+	print "append.label Appendable\n";
+	print "append.draw STACK\n";
+	print "append.info Volumes in appendable state\n";
 
-	GRAPHLIMIT=`echo "select maxvols from pool where poolid=$POOL;" | psql --pset t bacula | sed -e 's/ //g'`
+	print "used.label Used\n";
+	print "used.draw STACK\n";
+	print "used.info Volumes with state Used\n";
 
-	echo "graph_title Bacula Volumes from POOL $POOLNAME"
-	echo "graph_args --base 1000 -r --lower-limit 0 --upper-limit $GRAPHLIMIT"
-	echo 'graph_vlabel Number of volumes'
-	echo 'graph_category bacula'
-	echo "graph_info Bacula Volume states for POOL $POOLNAME"
-	echo 'graph_scale no'
-        echo 'graph_order full append error recycle other unused'
+	print "error.label Error\n";
+	print "error.draw STACK\n";
+	print "error.info Volumes with state Error\n";
 
-	echo 'full.label Full'
-	echo 'full.draw AREA'
-	echo 'full.info Full and retention time not reached'
+	print "recycle.label Recycleable\n";
+	print "recycle.draw STACK\n";
+	print "recycle.info Volumes which are recycleable\n";
 
-	echo 'append.label Appendable'
-	echo 'append.draw STACK'
-	echo 'append.info Volumes in appendable state'
+	print "other.label Others\n";
+	print "other.draw STACK\n";
+	print "other.info Volumes with other state\n";
 
-	echo 'error.label Error'
-	echo 'error.draw STACK'
-	echo 'error.info Volumes with state Error'
+	print "unused.label Unused\n";
+	print "unused.draw STACK\n";
+	print "unused.info Unused volumes\n";
 
-	echo 'recycle.label Recycleable'
-	echo 'recycle.draw STACK'
-	echo 'recycle.info Volumes which are recycleable'
+	print "maxvolumes.label Maximal volumes\n";
+	print "maxvolumes.draw LINE1\n";
+	print "maxvolumes.info Max Volumes\n";
 
-	echo 'other.label Others'
-	echo 'other.draw STACK'
-	echo 'other.info Volumes with other state'
-
-	echo 'unused.label Unused'
-	echo 'unused.draw STACK'
-	echo 'unused.info Unused volumes'
-
-	echo 'maxvolumes.label Maximal volumes'
-	echo 'maxvolumes.draw LINE1'
-	echo 'maxvolumes.info Max Volumes'
-
-
-	exit 0
-fi
+	$cursor->finish;
+	$dbh->disconnect();
+	exit(0);
+}
 
 # volstatus: Full, Archive, Append, Recycle, Read-Only, Disabled, Error, Busy
 
 # Full and retention time not reached
-FULL=`echo "select count(*) from media where poolid=$POOL and volstatus='Full' and (volretention||'seconds')::INTERVAL + lastwritten > NOW();" | psql --pset t bacula | sed -e 's/ //g'` 
+$query = "SELECT count(*) AS full FROM media WHERE poolid = ? AND volstatus = 'Full' and (volretention || 'seconds')::INTERVAL + lastwritten > NOW()";
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute($POOLID) || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $FULL = $data->{'full'} || 0;
 # Volmes which are appendable according to bacula
-APPEND=`echo "select count(*) from media where poolid=$POOL and volstatus='Append';" | psql --pset t bacula | sed -e 's/ //g'` 
+$query = "SELECT count(*) AS append FROM media WHERE poolid = ? AND volstatus = 'Append'";
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute($POOLID) || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $APPEND = $data->{'append'} || 0;
 # Error Volumes from Bacula
-ERROR=`echo "select count(*) from media where poolid=$POOL and volstatus='Error';" | psql --pset t bacula | sed -e 's/ //g'` 
+$query = "SELECT count(*) AS error FROM media WHERE poolid = ? AND volstatus = 'Error'";
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute($POOLID) || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $ERROR = $data->{'error'} || 0;
+# Used Volumes from Bacula
+$query = "SELECT count(*) AS used FROM media WHERE poolid = ? AND volstatus = 'Used'";
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute($POOLID) || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $USED = $data->{'used'} || 0;
 # Volumes wich are marked as recycleable or have reached their retention time
-RECYCLE=`echo "select count(*) from media where poolid=$POOL and (volstatus='Recycle' or (volretention||'seconds')::INTERVAL + lastwritten < NOW()) and volstatus!='Append';" | psql --pset t bacula | sed -e 's/ //g'` 
+$query = "SELECT count(*) AS recycle FROM media WHERE poolid = ? AND (volstatus = 'Recycle' OR (volretention || 'seconds')::INTERVAL + lastwritten < NOW()) AND volstatus != 'Append'";
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute($POOLID) || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $RECYCLE = $data->{'recycle'} || 0;
 # Volumes which are not in state appendable or error
-OTHER=`echo "select count(*) from media where poolid=$POOL and volstatus not in ('Full', 'Append', 'Error', 'Recycle');" | psql --pset t bacula | sed -e 's/ //g'`
+$query = "SELECT count(*) AS other FROM media WHERE poolid = ? AND volstatus NOT IN ('Used', 'Full', 'Append', 'Error', 'Recycle')";
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute($POOLID) || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $OTHER = $data->{'other'} || 0;
 # Unused and unlabeled
-UNUSED=`echo "select (select maxvols from pool where poolid=$POOL)-count(*) from media where poolid=$POOL;" | psql --pset t bacula | sed -e 's/ //g'`
-# Total Volumes
-TOTAL=`echo "select maxvols from pool where poolid=$POOL;" | psql --pset t bacula | sed -e 's/ //g'`
+$query = "SELECT CASE WHEN unused < 0 THEN 0 ELSE unused END AS unused FROM (SELECT (SELECT maxvols FROM pool WHERE poolid = ?) - COUNT(*) AS unused FROM media WHERE poolid = ?) AS sub";
+$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
+$cursor->execute($POOLID, $POOLID) || die ("Cannot execute ".$cursor->errstr."\n");
+$data = $cursor->fetchrow_hashref;
+my $UNUSED = $data->{'unused'} || 0;
 
-echo "full.value $FULL"
-echo "append.value $APPEND"
-echo "error.value $ERROR"
-echo "recycle.value $RECYCLE"
-echo "other.value $OTHER"
-echo "unused.value $UNUSED"
-echo "maxvolumes.value $TOTAL"
+print "full.value $FULL\n";
+print "append.value $APPEND\n";
+print "used.value $USED\n";
+print "error.value $ERROR\n";
+print "recycle.value $RECYCLE\n";
+print "other.value $OTHER\n";
+print "unused.value $UNUSED\n";
+print "maxvolumes.value $GRAPHLIMIT\n";
 
-exit 0
+$cursor->finish;
+$dbh->disconnect();
+
+exit(0);
